# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if GetDepend('SOC_SPACEMIT_K3_CORE0') == False:
    SrcRemove(src, ['spacemit-rproc_test_rcpu0.c'])

if GetDepend('SOC_SPACEMIT_K3_CORE1') == False:
    SrcRemove(src, ['spacemit-rproc_test_rcpu1.c'])

group = DefineGroup('Drivers_rproc', src, depend = ['BSP_USING_RPMSG'], CPPPATH = CPPPATH)

Return('group')
