# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
ControllerFunctions.c
''')
CPPPATH = [cwd]

group   = DefineGroup('ControllerFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
