# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
FilteringFunctions.c
FilteringFunctionsF16.c
''')
CPPPATH = [cwd]

group   = DefineGroup('FilteringFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
