from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')

CPPPATH = [cwd + '/../../inc']

group = DefineGroup('FDT', src, depend = ['RT_USING_FDT'], CPPPATH = CPPPATH)

Return('group')
