# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
TransformFunctions.c
TransformFunctionsF16.c
''')
CPPPATH = [cwd]

group   = DefineGroup('TransformFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
