# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
SVMFunctions.c
SVMFunctionsF16.c
''')
CPPPATH = [cwd]

group   = DefineGroup('SVMFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
