from building import *

# The set of source files associated with this SConscript file.
src = Split('''
''')
cwd = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('NmsisNN', src, depend = ['RT_USING_NMSIS_NN'], CPPPATH = CPPPATH)

if GetDepend('RT_USING_NMSIS_NN'):
	# search in the file system implementation
	list = os.listdir(cwd)
	for item in list:
		if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
			group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')

