# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Glob("*.c") 
CPPPATH = [cwd]

group   = DefineGroup('LSTMFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
