from building import *

# The set of source files associated with this SConscript file.
src = Split('''
''')
cwd = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('NmsisDispPrivateInclude', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

