from building import *

# The set of source files associated with this SConscript file.
src = Split('''
rpmsg_rpc_client.c
rpmsg_rpc_server.c
''')
cwd = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('OpenAMPSrcLibServiceRpmsgRpc', src, depend = ['RT_USING_OPENAMP'], CPPPATH = CPPPATH)

Return('group')

