# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
FastMathFunctions.c
FastMathFunctionsF16.c
''')
CPPPATH = [cwd]

group   = DefineGroup('FastMathFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
