# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
CPPPATH = [cwd]

src = [
	'ccu_mix.c',
	'ccu-fix-clk.c',
]
if GetDepend(['RT_USING_CLK', 'SOC_SPACEMIT_K1_X']):
	src += [
	'ccu_pll.c',
	'ccu-spacemit-k1x.c',
	]
if GetDepend(['RT_USING_CLK', 'SOC_SPACEMIT_K3']):
	src += [
	'ccu_ddn.c',
	'ccu_plla.c',
	'ccu-spacemit-k3.c',
	]

group = DefineGroup('CCUDrivers', src, depend = ['RT_USING_CLK'], CPPPATH = CPPPATH)

Return('group')
