# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
StatisticsFunctions.c
StatisticsFunctionsF16.c
''')
CPPPATH = [cwd]

group   = DefineGroup('StatisticsFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
