from building import *

# The set of source files associated with this SConscript file.
src = Split('''
elf_loader.c
remoteproc.c
remoteproc_virtio.c
rsc_table_parser.c
''')
cwd = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('OpenAMPSrcLibRemoteProc', src, depend = ['RT_USING_OPENAMP'], CPPPATH = CPPPATH)

Return('group')

