# RT-Thread building script for bridge
from building import *

# The set of source files associated with this SConscript file.
src = Glob('*.c')
cwd = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('ArmScpModuleMTimerInc', src, depend = ['BUILD_USING_MTIMER'], CPPPATH = CPPPATH)

Return('group')
