# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
SupportFunctions.c
SupportFunctionsF16.c
''')
CPPPATH = [cwd]

group   = DefineGroup('SupportFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
