Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if GetDepend('SOC_SPACEMIT_K1_X') == False:
    SrcRemove(src, ['uart_service.c'])

group   = DefineGroup('drv_uart', src, depend = ['BSP_USING_UART'], CPPPATH = CPPPATH)

Return('group')
