Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if GetDepend('SOC_SPACEMIT_K1_X') == False:
    SrcRemove(src, ['ir_service.c'])

group   = DefineGroup('drv_ir', src, depend = ['BSP_USING_IR'], CPPPATH = CPPPATH)

Return('group')
