# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('Drivers_i2c_service', src, depend = ['BSP_USING_I2C'], CPPPATH = CPPPATH)

Return('group')
