# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
InterpolationFunctions.c
InterpolationFunctionsF16.c
''')
CPPPATH = [cwd]

group   = DefineGroup('InterpolationFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
