# RT-Thread building script for bridge
from building import *

# The set of source files associated with this SConscript file.
src = Split('''
config_scmi_power_domain.c
''')
cwd = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('ArmScpModuleSCMIpowerDomainConfig', src, depend = ['BUILD_HAS_MOD_SCMI_POWER_DOMAIN'], CPPPATH = CPPPATH)

# if GetDepend('RT_USING_DFS'):
# search in the file system implementation
list = os.listdir(cwd)

if GetDepend('BUILD_HAS_MOD_SCMI_POWER_DOMAIN'):
	for item in list:
		if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
			group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')

