# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
DistanceFunctions.c
DistanceFunctionsF16.c
''')
CPPPATH = [cwd]

group   = DefineGroup('DistanceFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
