# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
BayesFunctions.c
BayesFunctionsF16.c
''')
CPPPATH = [cwd]

group   = DefineGroup('BayesFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
