# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if GetDepend('SOC_SPACEMIT_K1_X') == False:
    SrcRemove(src, ['adma_service.c'])

group = DefineGroup('Drivers_adma', src, depend = ['BSP_USING_ADMA'], CPPPATH = CPPPATH)

Return('group')
