# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
WindowFunctions.c
''')
CPPPATH = [cwd]

group   = DefineGroup('WindowFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
