/*
 * Copyright (c) 2022-2025, Spacemit
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __RISCV_CLINT_H__
#define __RISCV_CLINT_H__

#include "spacemit_sdk_soc.h"

#define DMAC_IRQn	SOC_INT19_IRQn
#define RSM_IRQn	SOC_INT23_IRQn
#define ADMA_CH0_IRQn	SOC_INT24_IRQn
#define ADMA_CH1_IRQn	SOC_INT25_IRQn
#define DFE_IRQn_SSPA_IRQn	SOC_INT26_IRQn
#define TIM0_IRQn	SOC_INT27_IRQn
#define TIM1_IRQn	SOC_INT28_IRQn
#define TIM2_IRQn	SOC_INT29_IRQn
#define IPC_AP2AUD_IRQn	SOC_INT30_IRQn
#define SHUBI2C0_INT_REQ_IRQn	SOC_INT32_IRQn
#define SHUBSSP0_INT_REQ_IRQn	SOC_INT34_IRQn
#define UART1_INT_REQ_IRQn	SOC_INT36_IRQn
#define AUD_OCP_INT_CLASSG_SHORTPWR_IRQn	SOC_INT37_IRQn
#define HOOK_KEY_IRQn	SOC_INT38_IRQn
#define AUD_PLUG_IRQn	SOC_INT39_IRQn
#define AUD_AP_WAKEUP_IRQn	SOC_INT41_IRQn
#define SENSOR_HUB_IRPC_IRQn	SOC_INT42_IRQn
#define GPIO_110_INT_PMIC_IRQn	SOC_INT43_IRQn
#define GPIO_115_IRQn		SOC_INT44_IRQn
#define GPIO_116_IRQn		SOC_INT45_IRQn
#define GPIO_117_IRQn		SOC_INT46_IRQn
#define GPIO_66_IRQn		SOC_INT47_IRQn
#define GPIO_67_IRQn		SOC_INT48_IRQn
#define GPIO_68_IRQn		SOC_INT49_IRQn
#define GPIO_69_IRQn		SOC_INT50_IRQn
#define ADMA1_CHI1_IRQn		SOC_INT52_IRQn
#define ADMA0_CH1_IRQn		SOC_INT53_IRQn
#define SSPA1_IRQn		SOC_INT54_IRQn
#define HDMI_ADMA_CH_IRQn	SOC_INT55_IRQn
#define aDMA0_CH1_IRQn		SOC_INT57_IRQn
#define ADMA0_CH0_IRQn		SOC_INT58_IRQn
#define SSPA0_IRQn		SOC_INT59_IRQn
#define CAN0_INT0_IRQn		SOC_INT60_IRQn
#define CAN0_INT1_IRQn		SOC_INT61_IRQn
#define IRC_IRQn		SOC_INT62_IRQn
#define UART_IRQn		SOC_INT63_IRQn
#define SHUB_EDGE_DET_IRQn	SOC_INT64_IRQn
	
#endif /* __RISCV_CLINT_H__ */
