# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('drvpinctrl', src, depend = ['BSP_USING_PIN'], CPPPATH = CPPPATH)

Return('group')
