# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('Drivers_spi_service', src, depend = ['BSP_USING_SPI'], CPPPATH = CPPPATH)

Return('group')
