from building import *

# The set of source files associated with this SConscript file.
src = Split('''
''')
cwd = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('OpenAMP', src, depend = ['RT_USING_OPENAMP'], CPPPATH = CPPPATH)

# search in the file system implementation
list = os.listdir(cwd)

if GetDepend('RT_USING_OPENAMP'):
	for item in list:
		if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
			group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')

