# RT-Thread building script for bridge
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Split('''
ComplexMathFunctions.c
ComplexMathFunctionsF16.c
''')
CPPPATH = [cwd]

group   = DefineGroup('ComplexMathFunctions', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
